import type { Metadata } from 'next'
import type { CSSProperties } from 'react'
import Link from 'next/link'

import { AgencyNav } from '@/components/agency/nav'
import { AgencyFooter } from '@/components/agency/footer'
import { TIER_LEGEND } from '@/data/agency/ledger'
import type { ProofTier } from '@/data/agency/case-studies'
import './method.css'

const METHOD_URL = 'https://agency.sageideas.dev/method'

export const metadata: Metadata = {
  title: 'Proof-Driven Delivery — The Method — Jason Teixeira',
  description:
    'Proof-Driven Delivery: every claim carries its artifact, unverified work is labeled, and "ready" is a file generated by a gate — not a feeling. The methodology this site runs on, written as a spec you can adopt.',
  alternates: { canonical: METHOD_URL },
}

/* ---------- the three tiers ---------- */

interface TierCard {
  tier: ProofTier
  accentVar: string
  definition: string
  qualifies: readonly string[]
  onThisSite: string
}

function legendLabel(tier: ProofTier): string {
  return TIER_LEGEND.find((entry) => entry.tier === tier)?.label ?? ''
}

const TIER_CARDS: readonly TierCard[] = [
  {
    tier: 'T1',
    accentVar: 'var(--acc-pass)',
    definition:
      'Evidence that runs somewhere you can reach without me: a live repository, a CI report, a deployed demo. T1 survives my laptop being off.',
    qualifies: [
      'A public repo you can clone and run',
      'A CI workflow with green (or honestly red) runs attached to real commits',
      'A production deploy you can click through yourself',
    ],
    onThisSite:
      'Case studies badged LIVE, and ledger rows whose artifact is a repo, workflow file, or public deploy.',
  },
  {
    tier: 'T2',
    accentVar: 'var(--acc-primary)',
    definition:
      'Evidence that exists as an artifact on disk — terminal output, a generated report, flow files, a runbook — but was produced locally. Real, inspectable, not yet independently re-runnable.',
    qualifies: [
      'A machine-generated report (never hand-edited) checked into a repo',
      'Terminal gate output or a coverage summary from a recorded run',
      'Generated files on disk — test flows, ledgers, diagrams — that back a claim',
    ],
    onThisSite:
      'Case studies badged LOCAL PROOF, and ledger rows whose artifact is a report, script output, or on-disk directory.',
  },
  {
    tier: 'T3',
    accentVar: 'var(--acc-fail)',
    definition:
      'A written explanation or planned work. No artifact yet — the claim exists only as prose. T3 is allowed on this site under one condition: it is labeled T3.',
    qualifies: [
      'A recorded result whose artifact must be regenerated before it can be quoted',
      'A design, plan, or runbook for work that has not run yet',
      'Anything where the honest answer to "show me" is a document, not an output',
    ],
    onThisSite:
      'Ledger rows marked T3 — like a device-cert number that honestly reads 0/256 until re-run — and every "improve next" note on the case studies.',
  },
]

/* ---------- the rules ---------- */

const RULES: readonly string[] = [
  'Every claim carries its artifact.',
  'Unverified work is labeled, not hidden.',
  "Gates generate verdicts — 'ready' is a file, not a feeling.",
  'The system verifies itself in CI.',
  'Corrections are published, not papered over.',
]

/* ---------- see it running ---------- */

interface RunningLink {
  label: string
  detail: string
  href: string
  external?: boolean
  note?: string
}

const RUNNING_LINKS: readonly RunningLink[] = [
  {
    label: 'THE HERO GATE',
    detail: 'The homepage opens with this site’s own release gate and its verdict.',
    href: '/',
  },
  {
    label: 'THE EVIDENCE LEDGER',
    detail: 'Every headline claim, its artifact, and its tier — one table.',
    href: '/#ledger',
  },
  {
    label: 'THE CI WORKFLOW',
    detail: 'The gate that produces the verdict, running on GitHub Actions.',
    href: 'https://github.com/JasonTeixeira/sageideas.dev/actions',
    external: true,
    note: '(public after launch)',
  },
]

export default function MethodPage() {
  return (
    <>
      <AgencyNav />
      <main>
        {/* hero */}
        <section className="ag-section ag-method-hero" aria-labelledby="method-heading">
          <p className="ag-kicker">THE METHOD</p>
          <h1 id="method-heading" className="ag-method-h1">
            Proof-Driven Delivery
          </h1>
          <p className="ag-method-sub">
            Proof-Driven Delivery is a way of shipping software where no claim outranks its
            evidence: every deliverable is attached to an artifact, every artifact is graded by how
            independently it can be verified, and readiness is a verdict a gate computes — never a
            feeling a person reports.
          </p>
        </section>

        {/* the three tiers */}
        <section className="ag-section" aria-labelledby="method-tiers-heading">
          <p className="ag-kicker">EVIDENCE GRADING</p>
          <h2 id="method-tiers-heading" className="ag-method-h2">
            The three tiers
          </h2>
          <p className="ag-method-lede">
            Not all evidence is equal, and pretending otherwise is how portfolios lie. Every claim
            here is graded T1, T2, or T3 — and the grade is displayed, including when it is the
            weakest one.
          </p>
          <div className="ag-grid ag-method-tiers">
            {TIER_CARDS.map((card) => (
              <article
                key={card.tier}
                className="ag-cell ag-method-tier"
                style={{ '--tier-accent': card.accentVar } as CSSProperties}
              >
                <div className="ag-method-tier-head">
                  <span className="ag-method-tier-id">{card.tier}</span>
                  <span className="ag-method-tier-label">{legendLabel(card.tier)}</span>
                </div>
                <p className="ag-method-tier-def">{card.definition}</p>
                <p className="ag-method-tier-sub">WHAT QUALIFIES</p>
                <ul className="ag-method-tier-list">
                  {card.qualifies.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
                <p className="ag-method-tier-sub">ON THIS SITE</p>
                <p className="ag-method-tier-site">{card.onThisSite}</p>
              </article>
            ))}
          </div>
        </section>

        {/* the rules */}
        <section className="ag-section" aria-labelledby="method-rules-heading">
          <p className="ag-kicker">THE CONTRACT</p>
          <h2 id="method-rules-heading" className="ag-method-h2">
            The rules
          </h2>
          <ol className="ag-method-rules">
            {RULES.map((rule, index) => (
              <li key={rule}>
                <span className="ag-method-rule-num">{String(index + 1).padStart(2, '0')}</span>
                <span className="ag-method-rule-text">{rule}</span>
              </li>
            ))}
          </ol>
        </section>

        {/* see it running */}
        <section className="ag-section" aria-labelledby="method-running-heading">
          <p className="ag-kicker">NOT A MANIFESTO</p>
          <h2 id="method-running-heading" className="ag-method-h2">
            See it running
          </h2>
          <p className="ag-method-lede">
            This page describes the system; these three surfaces are the system. If they ever
            disagree with the words above, trust the surfaces.
          </p>
          <div className="ag-grid ag-method-running">
            {RUNNING_LINKS.map((link) =>
              link.external ? (
                <a
                  key={link.label}
                  href={link.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="ag-cell ag-method-running-link"
                >
                  <span className="ag-method-running-label">
                    {link.label}
                    {link.note ? <span className="ag-method-running-note"> {link.note}</span> : null}
                  </span>
                  <span className="ag-method-running-detail">{link.detail}</span>
                  <span className="ag-method-running-arrow">↗</span>
                </a>
              ) : (
                <Link key={link.label} href={link.href} className="ag-cell ag-method-running-link">
                  <span className="ag-method-running-label">{link.label}</span>
                  <span className="ag-method-running-detail">{link.detail}</span>
                  <span className="ag-method-running-arrow">→</span>
                </Link>
              ),
            )}
          </div>
        </section>

        {/* closing CTA */}
        <section className="ag-section ag-method-cta" aria-label="Adopt the method">
          <div className="ag-method-cta-row">
            <Link href="/services" className="ag-btn ag-btn--solid">
              ADOPT IT ON YOUR TEAM →
            </Link>
            <Link href="/blog" className="ag-btn">
              READ THE FIELD NOTES →
            </Link>
          </div>
        </section>
      </main>
      <AgencyFooter />
    </>
  )
}
