/**
 * Welcome + onboarding voiceovers, narrated in Jason's cloned voice and served from
 * Supabase Storage (public bucket `academy-voice/welcome/`). Generated by
 * scripts/academy/voice/generate-welcome.mjs — keep this map in sync with
 * public/academy/voice/welcome/manifest.json when regenerating.
 */
export type WelcomeClip = {
  readonly url: string
  readonly ms: number
  readonly text: string
}

const BUCKET = 'https://hocrntqhgvmeaxwlhzwl.supabase.co/storage/v1/object/public/academy-voice/welcome'

export const WELCOME_AUDIO = {
  welcome: {
    url: `${BUCKET}/welcome.mp3`,
    ms: 24752,
    text: "Hey — welcome to Sage Academy. I'm Jason; I built this. Here's the honest version of what you're getting into: most platforms hand you a certificate for watching videos. We don't. Here you learn by doing — you'll frame a real problem, build the fix, and prove it holds with a check you can't hand-wave. Every course ends in evidence a reviewer would actually trust, not a badge. Start with one lesson, ship one proof — that's the whole game. Let's go.",
  },
  'onboard-goal': {
    url: `${BUCKET}/onboard-goal.mp3`,
    ms: 4412,
    text: "First, tell me what you're aiming at, and I'll point you at the right track — no filler.",
  },
  'onboard-loop': {
    url: `${BUCKET}/onboard-loop.mp3`,
    ms: 9009,
    text: "Every lesson runs the same loop senior engineers run on autopilot: frame it, map it, decide under tradeoffs, prove it. You'll feel it by lesson two.",
  },
  'onboard-first-win': {
    url: `${BUCKET}/onboard-first-win.mp3`,
    ms: 5526,
    text: "Here's your first lesson — small on purpose. Get one proof holding. That's the moment this clicks.",
  },
  'onboard-ledger': {
    url: `${BUCKET}/onboard-ledger.mp3`,
    ms: 12214,
    text: "Everything you prove lands in your ledger — that's your real portfolio. Pick any claim, follow the artifact. It's what makes a certificate here actually mean something.",
  },
} as const satisfies Record<string, WelcomeClip>

export type WelcomeClipKey = keyof typeof WELCOME_AUDIO
