// #1 RAG — CLEAR REWRITE (TEACHING_CLARITY.md structure)
export default [
  ['01', "Hey, welcome back. Today you're going to learn how to stop an AI from making things up and lying to your users. By the end, you'll understand a technique called RAG, and you'll know how to build an AI that answers from your real documents — or honestly admits when it doesn't know."],
  ['02', "First, let me show you the problem. Imagine you build a chatbot and connect it to your company's help docs. A customer asks it: what's your refund policy?"],
  ['03', "The AI answers, very confidently: you have thirty days to get a refund. Sounds perfect. There's just one problem — you never had a refund policy. The AI made it up. This is called a hallucination: it didn't know the answer, so it invented one that sounds right."],
  ['04', "Now, your first instinct might be to just use a smarter, more expensive model. But that doesn't fix it. A smarter model doesn't lie less — it just lies more convincingly. The real problem is that the AI is guessing, when it should be looking things up."],
  ['05', "So here's the fix. It's called RAG. Think about the difference between a closed-book exam and an open-book exam. Closed book, you answer from memory, and if you don't know, you guess. Open book, you look up the answer first, then write it down. RAG turns your AI from a closed-book student into an open-book one."],
  ['06', "Let's walk through how it works. It's just two steps: retrieve, then answer. Step one, retrieve. When a question comes in, we don't hand the AI the whole manual. We search the documents and pull out only the few paragraphs most relevant to that question."],
  ['07', "Step two, answer. We give those paragraphs to the AI along with the question, and one clear instruction: answer using only this text, and show where you found it. Because it's now reading from the real document, it stops guessing."],
  ['08', "But here's the part most tutorials skip. What if the customer asks something that isn't in your documents at all? A basic setup will still make something up. So we add one simple rule: if the answer isn't in the paragraphs we found, don't answer — just say, I don't have that information."],
  ['09', "Let me show you a real example. A customer asks: how long do I have to return an item? We search the docs and find the line: items can be returned within thirty days. We hand that to the AI, and it answers correctly — you have thirty days — with a link to the exact source."],
  ['10', "Now they ask something we don't cover: do you ship to the moon? This time the search finds nothing. So instead of inventing an answer, the AI says: I don't have information about that. Honest, and safe."],
  ['11', "Now, three common mistakes to avoid. One: bad chunking — that's cutting your documents in the wrong spot, like splitting a sentence in half. Cut on paragraphs instead. Two: trusting the search blindly — the closest match isn't always right, so re-order results by real relevance. Three, the big one: never testing it. Measure how often your answers are actually backed by the source."],
  ['12', "So let's recap what you learned today. One: AIs make things up because they guess instead of looking things up. Two: RAG fixes that by retrieving your real document first, then answering from it. Three: always let the AI say I don't know. And four: test that your answers are grounded in the source."],
  ['13', "If you want to build this exact system yourself, for free, right in your browser, head to sageideas dot dev slash academy. That's it for today. Proof, not paper. I'll see you in the next one."],
];
