import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'
import { REQUIRED_SECTIONS, type SprintIntensity } from '../../lib/academy/engine'
const slug = 'nextjs-supabase'
const lessons = JSON.parse(readFileSync(`data/academy/authoring/${slug}.lessons.json`, 'utf8')) as Record<string, Array<Record<string, unknown>>>
const solutionPath = `data/academy/authoring/${slug}.lab_solutions.json`; const solutions = existsSync(solutionPath) ? JSON.parse(readFileSync(solutionPath, 'utf8')) as Record<string, { language: string; code: string }> : {}
const sourcePath = `docs/academy/evidence/${slug}/sources.json`; const sources = existsSync(sourcePath) ? JSON.parse(readFileSync(sourcePath, 'utf8')) as Array<Record<string, unknown>> : []
function visit(value: unknown, fn: (item: Record<string, unknown>) => void) { if (Array.isArray(value)) return value.forEach((item) => visit(item, fn)); if (!value || typeof value !== 'object') return; fn(value as Record<string, unknown>); Object.values(value).forEach((item) => visit(item, fn)) }
test('Next.js and Supabase preserves 20 practical labs inside complete ordered mastery loops', () => { assert.equal(Object.keys(lessons).length, 20); assert.deepEqual(Object.keys(solutions), Object.keys(lessons)); for (const [key, blocks] of Object.entries(lessons)) { const contract = blocks.find((block) => block.type === 'sprint-contract'); assert(contract, key); const types = blocks.map((block) => block.type); const required = REQUIRED_SECTIONS[contract.intensity as SprintIntensity]; required.forEach((type) => assert(types.includes(type), `${key}: ${type}`)); assert.deepEqual(required.map((type) => types.indexOf(type)).sort((a,b)=>a-b), required.map((type)=>types.indexOf(type))); const lab=blocks.find((block)=>block.type==='lab'); assert.equal(lab?.language,'js'); assert.equal(solutions[key].language,'js'); assert(String(lab?.starter).length>500); assert.match(String(lab?.starter),/TODO/i); assert.match(String(lab?.starter),/practice feedback/i); assert(String(lab?.summary).length>150); assert.match(solutions[key].code,/(function|=>)/); assert(!/console\.log\([^\n]*check/i.test(solutions[key].code)); const gate=blocks.find((block)=>block.type==='unlock-gate'); assert(Array.isArray(gate?.criteria)&&gate.criteria.length>=5) } })
test('every Next.js and Supabase JavaScript reference satisfies its exact observable contract',()=>{ for(const [key,blocks] of Object.entries(lessons)){const result=spawnSync(process.execPath,['-e',solutions[key].code],{encoding:'utf8',timeout:10_000});assert.equal(result.status,0,`${key}: ${result.stderr}`);assert.equal(result.stderr,'');assert.equal(result.stdout.trimEnd(),String(blocks.find((block)=>block.type==='lab')?.check).trimEnd(),`${key}: output drift`)}})
test('Next.js and Supabase gives security, consistency, deployment, and composition deep pacing',()=>{for(const key of ['server-actions','forms-validation','revalidation-caching','ssr-auth-sessions','row-level-security','writes-transactions','realtime','storage','env-secrets','deploy-vercel']){const c=lessons[key].find((b)=>b.type==='sprint-contract');assert.equal(c?.intensity,'deep');assert.match(String(c?.time),/2.*4/i)}const blocks=lessons['capstone-rls-crud'];const c=blocks.find((b)=>b.type==='sprint-contract');assert.equal(c?.intensity,'capstone');assert.match(String(c?.time),/multi-day/i);assert(blocks.findIndex((b)=>b.type==='calibration')<blocks.findIndex((b)=>b.type==='transfer'))})
test('Next.js and Supabase retains complete narration media metadata',()=>{let say=0,audio=0;visit(lessons,(item)=>{if(typeof item.say==='string'){assert(item.say.trim().length>20);say++}if(typeof item.audio==='string'){assert.match(item.audio,/^https:\/\//);audio++}});assert(say>=140);assert.equal(audio,say)})
test('Next.js and Supabase has a unique primary and official source ledger',()=>{assert(sources.length>=18);assert.equal(new Set(sources.map((s)=>s.source_id)).size,sources.length);for(const s of sources){assert.equal(s.source_tier,1);assert.match(String(s.url),/^https:\/\//);assert.match(String(s.retrieved_at),/^\d{4}-\d{2}-\d{2}$/)}})
test('Next.js and Supabase lesson sequence remains canonical registry truth',()=>{const registry=JSON.parse(readFileSync('data/academy/registry.json','utf8')) as {courses:Array<{slug:string;lessons:Array<{slug:string}>}>};const course=registry.courses.find((c)=>c.slug===slug);assert(course);assert.deepEqual(course.lessons.map((l)=>l.slug),Object.keys(lessons))})
test('Academy audit includes the Next.js and Supabase mastery contract',()=>assert.match(JSON.parse(readFileSync('package.json','utf8')).scripts['academy:audit:test'],/nextjs-supabase-mastery\.test\.ts/))
