import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'
import { REQUIRED_SECTIONS, type SprintIntensity } from '../../lib/academy/engine'
import { loadFlagshipCompetencyGraph } from '../../lib/academy/flagship-competency-graph'
const slug='rag-retrieval'
const lessons=JSON.parse(readFileSync(`data/academy/authoring/${slug}.lessons.json`,'utf8')) as Record<string,Array<Record<string,unknown>>>
const solutions=JSON.parse(readFileSync(`data/academy/authoring/${slug}.lab_solutions.json`,'utf8')) as Record<string,{language:string;code:string;stdin?:string}>
const sourcePath=`docs/academy/evidence/${slug}/sources.json`,sources=existsSync(sourcePath)?JSON.parse(readFileSync(sourcePath,'utf8')) as Array<Record<string,unknown>>:[]
function visit(v:unknown,fn:(x:Record<string,unknown>)=>void){if(Array.isArray(v))return v.forEach(x=>visit(x,fn));if(!v||typeof v!=='object')return;fn(v as Record<string,unknown>);Object.values(v).forEach(x=>visit(x,fn))}
test('RAG Retrieval implements one ordered novice-scaffolded mastery loop in all 20 lessons',()=>{assert.equal(Object.keys(lessons).length,20);assert.deepEqual(Object.keys(solutions),Object.keys(lessons));for(const [key,b] of Object.entries(lessons)){const c=b.find(x=>x.type==='sprint-contract');assert(c);const types=b.map(x=>x.type),req=REQUIRED_SECTIONS[c.intensity as SprintIntensity];req.forEach(x=>assert(types.includes(x),`${key}: ${x}`));assert.deepEqual(req.map(x=>types.indexOf(x)).sort((a,b)=>a-b),req.map(x=>types.indexOf(x)));['worked-example','debug','tradeoff','calibration','unlock-gate'].forEach(x=>assert(types.includes(x)));const lab=b.find(x=>x.type==='lab');assert.equal(lab?.language,'js');assert.equal(solutions[key].language,'js');assert(String(lab?.summary??'').length>150);assert(String(lab?.starter??'').length>700);assert.match(String(lab?.starter??''),/TODO/i);assert.match(String(b.find(x=>x.type==='debug')?.task??''),/regression/i);const gate=b.find(x=>x.type==='unlock-gate');assert(Array.isArray(gate?.criteria)&&gate.criteria.length>=5);assert.match(String(gate?.practiceOnlyNotice??''),/practice/i)}})
test('every RAG Retrieval reference satisfies its exact observable contract',()=>{let n=0;for(const [key,b] of Object.entries(lessons)){const s=solutions[key];assert(s,`${key}: missing reference`);const r=spawnSync('node',['-e',s.code],{encoding:'utf8',input:s.stdin??'',timeout:10000});assert.equal(r.status,0,`${key}: ${r.stderr}`);assert.equal(r.stderr,'');assert.equal(r.stdout.trimEnd(),String(b.find(x=>x.type==='lab')?.check).trimEnd(),`${key}: output drift`);n++}assert.equal(n,20)})
test('RAG Retrieval culminates in a multi-day grounded cited capstone',()=>{const b=lessons['capstone-grounded-cited-rag'],c=b.find(x=>x.type==='sprint-contract');assert.equal(c?.intensity,'capstone');assert.match(String(c?.time),/multi-day/i);assert(b.findIndex(x=>x.type==='calibration')<b.findIndex(x=>x.type==='transfer'))})
test('RAG Retrieval preserves narration text without promising missing media',()=>{let say=0,audio=0;visit(lessons,x=>{if(typeof x.say==='string'){assert(x.say.trim().length>20);say++}if(typeof x.audio==='string')audio++});assert(say>=100);assert.equal(audio,0)})
test('RAG Retrieval has a unique primary and official source ledger',()=>{assert(existsSync(sourcePath));assert(sources.length>=16);assert.equal(new Set(sources.map(x=>x.source_id)).size,sources.length);for(const s of sources){assert.equal(s.source_tier,1);assert.match(String(s.url),/^https:\/\//);assert.match(String(s.retrieved_at),/^\d{4}-\d{2}-\d{2}$/)}})
test('retrieval-systems mapping enumerates every RAG Retrieval lesson',()=>{const m=loadFlagshipCompetencyGraph(process.cwd()).competencies.find(x=>x.id==='retrieval-systems')?.courseMappings.find(x=>x.courseSlug===slug);assert(m);assert.deepEqual(m.lessonSlugs,Object.keys(lessons))})
test('Academy audit includes RAG Retrieval mastery contract',()=>{assert.match(JSON.parse(readFileSync('package.json','utf8')).scripts['academy:audit:test'],/rag-retrieval-mastery\.test\.ts/)})
