import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'
import { REQUIRED_SECTIONS, type SprintIntensity } from '../../lib/academy/engine'
const slug='stripe-auth'
const lessons=JSON.parse(readFileSync(`data/academy/authoring/${slug}.lessons.json`,'utf8')) as Record<string,Array<Record<string,unknown>>>
const solutions=JSON.parse(readFileSync(`data/academy/authoring/${slug}.lab_solutions.json`,'utf8')) as Record<string,{language:string;code:string}>
const sourcePath=`docs/academy/evidence/${slug}/sources.json`;const sources=existsSync(sourcePath)?JSON.parse(readFileSync(sourcePath,'utf8')) as Array<Record<string,unknown>>:[]
function visit(value:unknown,fn:(item:Record<string,unknown>)=>void){if(Array.isArray(value))return value.forEach((item)=>visit(item,fn));if(!value||typeof value!=='object')return;fn(value as Record<string,unknown>);Object.values(value).forEach((item)=>visit(item,fn))}
test('Stripe/Auth preserves 20 practical labs inside complete ordered security mastery loops',()=>{assert.equal(Object.keys(lessons).length,20);assert.deepEqual(Object.keys(solutions),Object.keys(lessons));for(const[key,blocks]of Object.entries(lessons)){const contract=blocks.find((b)=>b.type==='sprint-contract');assert(contract,key);const types=blocks.map((b)=>b.type);const required=REQUIRED_SECTIONS[contract.intensity as SprintIntensity];required.forEach((type)=>assert(types.includes(type),`${key}: ${type}`));assert.deepEqual(required.map((t)=>types.indexOf(t)).sort((a,b)=>a-b),required.map((t)=>types.indexOf(t)));const lab=blocks.find((b)=>b.type==='lab');assert.equal(lab?.language,'js');assert.equal(solutions[key].language,'js');assert(String(lab?.starter).length>500);assert.match(String(lab?.starter),/TODO|your code/i);assert.match(String(lab?.starter),/practice feedback/i);assert(String(lab?.summary).length>150);const gate=blocks.find((b)=>b.type==='unlock-gate');assert(Array.isArray(gate?.criteria)&&gate.criteria.length>=5);assert.match(String(gate?.practiceOnlyNotice),/practice/i)}})
test('every Stripe/Auth JavaScript reference satisfies its exact observable contract',()=>{for(const[key,blocks]of Object.entries(lessons)){const wrapped=`(async()=>{${solutions[key].code}\n})().catch(error=>{console.error(error);process.exit(1)})`;const result=spawnSync(process.execPath,['-e',wrapped],{encoding:'utf8',timeout:10_000});assert.equal(result.status,0,`${key}: ${result.stderr}`);assert.equal(result.stderr,'');assert.equal(result.stdout.trimEnd(),String(blocks.find((b)=>b.type==='lab')?.check).trimEnd(),`${key}: output drift`)}})
test('Stripe/Auth gives identity, authorization, webhook, billing-state, and recovery work deep pacing',()=>{for(const key of ['password-storage-oauth','protecting-routes-server-side','hosted-checkout','test-mode-key-hygiene','webhooks-source-of-truth','verifying-webhook-signatures','idempotent-handlers','reconciling-state','subscription-lifecycle','failed-payments-dunning','entitlements','pci-scope','refunds-cancellation']){const c=lessons[key].find((b)=>b.type==='sprint-contract');assert.equal(c?.intensity,'deep');assert.match(String(c?.time),/2.*4/i)}const blocks=lessons['capstone-signup-pay-access'];const c=blocks.find((b)=>b.type==='sprint-contract');assert.equal(c?.intensity,'capstone');assert.match(String(c?.time),/multi-day/i);assert(blocks.findIndex((b)=>b.type==='calibration')<blocks.findIndex((b)=>b.type==='transfer'))})
test('Stripe/Auth threat coverage fails closed at every sensitive boundary',()=>{const text=JSON.stringify({lessons,solutions}).toLowerCase();for(const pattern of [/constant.?time/,/raw body/,/signature/,/stale|replay/,/idempot/,/server.?side/,/source of truth/,/service.?role|secret key/,/authorization/,/refund/])assert.match(text,pattern)})
test('Stripe/Auth security examples use current password work factors and constant-time webhook checks',()=>{assert.match(solutions['password-storage-oauth'].code,/pbkdf2Sync\([^)]*600000/);assert.doesNotMatch(JSON.stringify(lessons['password-storage-oauth']),/50_?000|100_?000/);for(const key of ['verifying-webhook-signatures','capstone-signup-pay-access']){assert.match(solutions[key].code,/timingSafeEqual/);assert.match(solutions[key].code,/Math\.abs\(now-ts\)/)}})
test('Stripe/Auth retains complete narration media metadata',()=>{let say=0,audio=0;visit(lessons,(item)=>{if(typeof item.say==='string'){assert(item.say.trim().length>20);say++}if(typeof item.audio==='string'){assert.match(item.audio,/^https:\/\//);audio++}});assert(say>=140);assert.equal(audio,say)})
test('Stripe/Auth has a unique primary and official source ledger',()=>{assert(sources.length>=18);assert.equal(new Set(sources.map((s)=>s.source_id)).size,sources.length);for(const s of sources){assert.equal(s.source_tier,1);assert.match(String(s.url),/^https:\/\//);assert.match(String(s.retrieved_at),/^\d{4}-\d{2}-\d{2}$/)}})
test('Stripe/Auth lesson sequence remains canonical registry truth',()=>{const registry=JSON.parse(readFileSync('data/academy/registry.json','utf8')) as {courses:Array<{slug:string;lessons:Array<{slug:string}>}>};const course=registry.courses.find((c)=>c.slug===slug);assert(course);assert.deepEqual(course.lessons.map((l)=>l.slug),Object.keys(lessons))})
test('Academy audit includes the Stripe/Auth mastery contract',()=>assert.match(JSON.parse(readFileSync('package.json','utf8')).scripts['academy:audit:test'],/stripe-auth-mastery\.test\.ts/))
