// Single-source icon mapping for pipeline stages.
// Keeping this in one file lets us tree-shake and avoid sprinkling lucide
// imports across every consumer.

import {
  Compass,
  Phone,
  Search,
  PenLine,
  Palette,
  Layers,
  Wrench,
  Rocket,
  ShieldCheck,
  Sparkles,
  Monitor,
  Activity,
  Workflow,
  Bot,
  BarChart3,
  Package,
  MessageSquare,
  FileText,
  CheckCircle,
  Flag,
  RefreshCw,
  Send,
  Beaker,
  Globe,
  Database,
  Cog,
  Gauge,
  Lock,
  Eye,
  Megaphone,
  MousePointer,
  Play,
  type LucideIcon,
} from 'lucide-react'
import type { PipelineIcon } from './types'

export const PIPELINE_ICON_MAP: Record<PipelineIcon, LucideIcon> = {
  compass: Compass,
  phone: Phone,
  search: Search,
  'pen-line': PenLine,
  palette: Palette,
  layers: Layers,
  wrench: Wrench,
  rocket: Rocket,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  monitor: Monitor,
  activity: Activity,
  workflow: Workflow,
  bot: Bot,
  'bar-chart': BarChart3,
  package: Package,
  'message-square': MessageSquare,
  'file-text': FileText,
  'check-circle': CheckCircle,
  flag: Flag,
  'refresh-cw': RefreshCw,
  send: Send,
  beaker: Beaker,
  globe: Globe,
  database: Database,
  cog: Cog,
  gauge: Gauge,
  lock: Lock,
  eye: Eye,
  megaphone: Megaphone,
  'mouse-pointer': MousePointer,
  play: Play,
}
