// gen-icons.mjs — bundle a broad, teaching-relevant subset of lucide (MIT) into
// library/icons.js as { name: innerSVG } with stroke=currentColor so any node/concept
// gets a symbol on the tokens. Run: node scripts/gen-icons.mjs
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const dir = path.join(root, 'node_modules', 'lucide-static', 'icons');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.svg'));

// keep icons whose name contains any of these — broad coverage of teaching concepts
const KEEP = ['server','database','cloud','cpu','network','router','hard-drive','disc','box','boxes','container','layers','git','code','terminal','braces','binary','bug','shield','lock','key','fingerprint','scan','user','users','bot','brain','message','mail','send','share','link','globe','wifi','signal','activity','zap','gauge','timer','clock','calendar','trending','chart','bar','line','pie','file','folder','archive','search','filter','funnel','sort','list','grid','table','workflow','git-branch','git-merge','split','shuffle','repeat','refresh','rotate','arrow','move','check','x','alert','circle','triangle','square','hexagon','octagon','plus','minus','eye','flag','bookmark','star','heart','flame','sparkles','wand','rocket','target','crosshair','map','pin','compass','route','package','truck','store','credit-card','dollar','coins','wallet','banknote','receipt','percent','calculator','scale','beaker','flask','atom','microscope','dna','test-tube','battery','plug','power','lightbulb','settings','sliders','tool','wrench','hammer','cog','play','pause','skip','fast','volume','mic','camera','image','video','film','monitor','smartphone','laptop','tablet','keyboard','mouse','printer','headphones','book','graduation','pen','pencil','edit','clipboard','folder-tree','sitemap','component','layout','columns','rows','panel','maximize','minimize','expand','shrink','download','upload','import','export','cloud-upload','cloud-download','lock-open','unlock','history','undo','redo','loader','hourglass','trophy','award','medal','thumbs','smile','frown','help','info','ban','shield-check','shield-alert','key-round','door','building','factory','warehouse','antenna','satellite','radio','cast','bluetooth','usb','memory-stick','microchip','circuit','waypoints','spline','vector','pointer','hand','grip','anchor','magnet','orbit','radar','waves','wind','droplet','snowflake','sun','moon','cloud-rain','thermometer'];

const wanted = new Set();
for (const f of files) { const n = f.replace('.svg', ''); if (KEEP.some(k => n.includes(k))) wanted.add(n); }

const ICONS = {};
for (const n of wanted) {
  let svg = fs.readFileSync(path.join(dir, n + '.svg'), 'utf8');
  // strip outer <svg ...> ... </svg>, keep inner shapes (they inherit stroke)
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\n\s*/g, '');
  ICONS[n] = inner;
}
const names = Object.keys(ICONS).sort();
const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — ${names.length} lucide icons (MIT), inner SVG, stroke=currentColor.\n`
  + `export const ICONS = ${JSON.stringify(ICONS)};\n`
  + `export const ICON_NAMES = ${JSON.stringify(names)};\n`
  + `// icon(name, size, stroke) -> full <svg>\n`
  + `export const icon = (name, size = 48, sw = 2) => ICONS[name] ? \`<svg viewBox="0 0 24 24" width="\${size}" height="\${size}" fill="none" stroke="currentColor" stroke-width="\${sw}" stroke-linecap="round" stroke-linejoin="round">\${ICONS[name]}</svg>\` : '';\n`;
fs.writeFileSync(path.join(root, 'library', 'icons.js'), out);
console.log(`✓ library/icons.js — ${names.length} icons bundled (${(out.length / 1024).toFixed(0)}KB)`);
